# Generated by Django 5.0.7 on 2024-07-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upload",
            old_name="json",
            new_name="json_data",
        ),
    ]
