# Generated by Django 5.0.7 on 2024-07-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_remove_upload_json_data_upload_file_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
