# Generated by Django 5.0.7 on 2024-07-16 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_alter_data_options_rename_sensor_data_sensorid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("mapping", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="upload",
            name="field_mapping",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.fieldmapping",
            ),
        ),
    ]
