# Generated by Django 5.0.7 on 2024-07-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_alter_fieldmapping_mapping"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="data",
            unique_together={("timestamp", "sensorid")},
        ),
    ]
